runtime: php55
api_version: 1

handlers:
- url: /
  script: login.php

- url: /index\.html
  script: login.php

- url: /index\.php
  script: login.php

- url: /stylesheets
  static_dir: stylesheets

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

#- url: /admin/.*
#  script: admin.php
#  login: admin

- url: /.*
  script: not_found.php